//based on the date the user input ex (2023-12-21), gives you the info of that date aka
// date, title, bio, img
// for the date page



const astronomyData = (date, callback ) => {
    const url = 'https://api.nasa.gov/planetary/apod?api_key=QOeP5NpXEklQLQfszDMeP3SXy72Y1iV8b5bAhe3G&date=' + date;
    const options = {
        method: 'GET',
        headers: {
            accept: 'application/json'
        }
    }

    // Return the promise generated by fetch
    return fetch(url, options)
        .then(res => res.json())
        .then(json => {
            const results =  {
                date: json.date,
                title: json.title,
                bio: json.explanation,
                img: json.url
            };
            if(results.date==undefined){
                return callback('Please enter a valid date', undefined)
            }
            callback (undefined , results)
        })

};


module.exports = astronomyData;

