// shows the picture of the day, as the default date is todays date.

const astronomyStatic = () => {
    const url = 'https://api.nasa.gov/planetary/apod?api_key=QOeP5NpXEklQLQfszDMeP3SXy72Y1iV8b5bAhe3G&date';
    const options = {
        method: 'GET',
        headers: {
            accept: 'application/json'
        }
    }

    // Return the promise generated by fetch
    return fetch(url, options)
        .then(res => res.json())
        .then(json => {
            return {
                date: json.date,
                title: json.title,
                bio: json.explanation,
                img: json.url
            };
        })
        .catch(err => {
            throw new Error('Error with data')
        });
}


module.exports = astronomyStatic;